<?php
namespace Tests\Models;

use \Models\User;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-13 at 08:29:52.
 * @group models
 */
class UserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

	public function testGetById()
	{
		$actual = $this->object->getById(673370);

		$msg = 'User::getById returns wrong result';
		$this->assertSame($this->object, $actual, $msg);

		$expected = [
			'first_name' => 'Зураб',
			'last_name'  => 'Хургидзе',
			'patronymic' => 'Азамович',
			'id'         => 673370,
			'hash'       => '7fc0a4f423d33f2102a85f67e366d5be'
		];

		$properties = [
			'first_name' => '',
			'last_name' => '',
			'patronymic' => '',
			'id' => '',
			'hash' => ''
		];
		$this->object->getProperties($properties);

		$msg = 'User::getById wrong behavior';
		$this->assertSame($expected, $properties, $msg);
    }
}
